Dev
TommyM0ntana/TheNewsPaper pull request #1
Opened 2019-10-17 16:34 UTC by TommyM0ntana

2019-10-17 21:54 UTC, Forison reviewed
# pull request under review by Forison

2019-10-17 22:35 UTC, Forison requested changes
## Good Job @TommyM0ntana 👋
I nearly felt I was on the original [newsweek](newsweek.com) website.🙂 You have done a great job, so far.
let us do these few changes so we can have our project approved.🙂

* [ ] The titles(top stories, features stories) are not seen at MD, SM, XS.🙂
This is how it looks currently ⬇️

![Screenshot from 2019-10-17 18-02-43](https://user-images.githubusercontent.com/29695661/67051198-7ff05500-f108-11e9-8526-d005cbc7d131.png)
![Screenshot from 2019-10-17 18-02-54](https://user-images.githubusercontent.com/29695661/67051201-7ff05500-f108-11e9-9ce9-b8294c0854ec.png)
 This is a result of the fixed nature of the navbar. make sure you have given appropriate margin-top(50-70px) to``` <main>```  to avoid this.

* [ ] let us make the subscribe button better by giving it this class ```.btn btn-light```🙂

* [ ] currently project ends at "FEATURED SLIDESHOWS". Let us add the remaining elements as found on the [newsweek](newsweek.com) page🙂

* [ ] let us fix the images in the magazine section. This is how they look like currently at  ```xs``` and ```sm```⬇️

![Screenshot from 2019-10-17 18-13-10](https://user-images.githubusercontent.com/29695661/67053294-eaa48f00-f10e-11e9-9b98-55946fde0d65.png)
![Screenshot from 2019-10-17 18-13-17](https://user-images.githubusercontent.com/29695661/67053295-eaa48f00-f10e-11e9-8f8d-a4f02b6b8c3d.png)

this is because you gave your image height. Set the height to auto and give it bootstrap class ```img-responsive``` 

* [ ] Let us add these parts to our project ⬇️

![Screenshot from 2019-10-17 18-23-12](https://user-images.githubusercontent.com/29695661/67053216-aca76b00-f10e-11e9-8c57-4708d30c47bb.png)
![Screenshot from 2019-10-17 18-23-19](https://user-images.githubusercontent.com/29695661/67053217-aca76b00-f10e-11e9-8ad5-aa7100fffc62.png)
![Screenshot from 2019-10-17 18-23-23](https://user-images.githubusercontent.com/29695661/67053218-ad400180-f10e-11e9-93e6-5c24c77b7c06.png)

refer to [newsweek](newseek.com) check how these elements behave at each breakpoint

* [ ] let us check our footer and make changes to it  🙂
![Screenshot from 2019-10-17 18-28-13](https://user-images.githubusercontent.com/29695661/67052481-546f6980-f10c-11e9-955e-c15d458edc85.png)
refer to [newsweek](newseek.com) check how this element behave at each breakpoint

* note: > let us try to have the elements in each section behave as it does on the [Newsweek (newsweek.com) page

## Kindly do these changes and submit the project for review

feel free to contact me on [LinkedIn](https://www.linkedin.com/in/forison-addo-558201159/), [Twitter](https://twitter.com/ADDOBOAKYE1) or slack for further clarification if necessary. i would be happy to assist you.

Happy coding😇😇😇

2019-10-17 22:58 UTC, Forison commented on style.css
> +  text-align: right;
you can use ```.text-left``` bootsrap class

2019-10-23 22:43 UTC, shloch commented
Hello @TommyM0ntana 
You can approve this Pull Request

Corrections have been made, GREAT JOB 👏👏👏👏

Happy Coding for your next step

2019-10-31 14:42 UTC, merged